// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "elgaot":return img`
................................
................................
................................
................................
................................
................................
.........f.....f................
........f4f...f4f...............
........f44fff44f...............
.......f44f444f44f..............
.......f444444444f..............
.......f44f444f44f....fff.......
.......f44f4f4f44f....f4f.......
........f44f4f44f22222f4f.......
........f444444ff22222444f......
.........2222222222222444f......
.........f42222244ffff444f......
.........f444444444f4444ff......
.........f444444444f44fff.......
.........f444444444fff..........
.........fffffffffff............
.........fffffffffff............
.........fff.....fff............
.........f4f.....f4f............
.........fff.....fff............
................................
................................
................................
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
