@namespace
class SpriteKind:
    UI = SpriteKind.create()

def on_overlap_tile(sprite, location):
    global coffeecheck
    coffeecheck = 1
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        myTile6
        """),
    on_overlap_tile)

def on_a_pressed():
    Quest.say_text(CurrentQuest, 500, False)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_overlap_tile2(sprite2, location2):
    global shiplaunch
    shiplaunch = 1
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        myTile16
        """),
    on_overlap_tile2)

def on_overlap_tile3(sprite3, location3):
    global EscapeDoor
    EscapeDoor = 1
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        myTile10
        """),
    on_overlap_tile3)

EscapeDoor = 0
CurrentQuest = ""
Quest: Sprite = None
shiplaunch = 0
coffeecheck = 0
coffeecheck = 0
Cat = sprites.create(assets.image("""
    elgaot
    """), SpriteKind.player)
scene.camera_follow_sprite(Cat)
tiles.set_current_tilemap(tilemap("""
    space station
    """))
tiles.place_on_tile(Cat, tiles.get_tile_location(13, 3))
scene.set_background_image(img("""
    f
    """))
shiplaunch = 0
Cat.say_text("*stretch*", 3500, True)
animation.run_image_animation(Cat,
    [img("""
            ................................
            ................................
            ................................
            ......f.....f...................
            ......ff...ff...................
            .....f44fff44f..................
            ....f44ff4ff44f.................
            ....f444444444f...fff...........
            ....f44f444f44f...f4f...........
            ....f44f4f4f442222f4f...........
            .....f44f4f44f2222444f..........
            .....f444444ff2222444f..........
            .....f42222244ffff444f..........
            .....f444444444f4444ff..........
            .....f444444444f44fff...........
            .....f444444444fff..............
            .....fffffffffff................
            .....fffffffffff................
            ....fff......fffff..............
            ...f4f......f4fffff.............
            ..fff......fff..f44f............
            ..fff......fff...fff............
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            """),
        img("""
            ................................
            ................................
            .....f.....f....................
            .....ff...ff....................
            ....f44fff44f...................
            ...f44f444f44f..................
            ...f444444444f..................
            ...f44f444f44f....fff...........
            ...f44f4f4f44f....f4f...........
            ....f44f4f44f22222f4f...........
            ....f444444ff22222444f..........
            .....2222222222222444f..........
            .....f42222244ffff444f..........
            .....f444444444f4444ff..........
            .....f444444444f44fff...........
            .....f444444444fff..............
            .....fffffffffff................
            .....fffffffffff................
            .....fff.....fff................
            .....f4f.....f4f................
            .....fff.....fff................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            """)],
    2000,
    True)
pause(4000)
Cat.say_text("looks like im the first awake, ill go grab a cup of coffee.",
    5000,
    True)
animation.run_image_animation(Cat,
    [img("""
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ........f.....f.................
            ........ff...ff.................
            .......f44fff44f................
            ......f44f444f44f...............
            ......f444444444f...............
            ......f44f444f44f....fff........
            ......f44f4f4f44f....f4f........
            .......f44f4f44f22222f4f........
            .......f444444ff22222444f.......
            ........2222222222222444f.......
            ........f42222244ffff444f.......
            ........f444444444f4444ff.......
            ........f444444444f44fff........
            ........f444444444fff...........
            ........fffffffffff.............
            ........fffffffffff.............
            ........fff.....fff.............
            ........f4f.....f4f.............
            ........fff.....fff.............
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            """),
        img("""
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            .........f.....f................
            .........ff...ff................
            ........f44fff44f...............
            .......f44f444f44f..............
            3......f444444444f...fff........
            .......f44f444f44f...f4f........
            .......f44f4f4f44f.22f4f........
            ........f44f4f44f2222444f.......
            ........f444444ff2222444f.......
            ........f42222244ffff444f.......
            ........f444444444f4444ff.......
            ........f444444444f44fff........
            ........f444444444fff...........
            ........fffffffffff.............
            ........fffffffffff.............
            ........fff.....fff.............
            ........f4f.....f4f.............
            ........fff.....fff.............
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            """)],
    1,
    True)
pause(5500)
animation.stop_animation(animation.AnimationTypes.ALL, Cat)
Quest = sprites.create(img("""
        . . . . . . . . . . . . e . . .
        . . . e e e e e e e e e . . . .
        . . e d d d d d d d d e . . . .
        . . . e d e d e d e e e . . . .
        . . . e e d e d e d d e . . . .
        . . . e d d d d d d d e e . . .
        . . . e e e d e e e e e e . . .
        . . . e d d e d e d e e e . . .
        . . . e d d d d d d d d e . . .
        . . . e e e d d e e e e e . . .
        . . . e e e e e e d e e e . . .
        . . . e d d d d d d d d e e . .
        . . . . e e e e e e e e . . . .
        . . e e . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        """),
    SpriteKind.UI)
Quest.set_position(101, 38)
Quest.follow(Cat, 90)
Quest.say_text("Press \"Space\" For Objective Details.", 2000, False)
controller.move_sprite(Cat, 50, 50)
CurrentQuest = "Find coffee"

def on_pause_until():
    pass


effects.confetti.start_screen_effect()
tiles.set_current_tilemap(tilemap("""
    level3
    """))
tiles.place_on_tile(Cat, tiles.get_tile_location(3, 12))
music.play(music.melody_playable(music.beam_up),
    music.PlaybackMode.IN_BACKGROUND)
pause(1500)
Cat.say_text("Uhhhh... Whats that sound??", 2500, False)
pause(3000)
Cat.say_text("AHHH! THE SHIPS GONNA EXPLODE!", 2500, False)
scene.camera_shake(5, 15000)
controller.move_sprite(Cat, 100, 100)
EscapeDoor = 0
CurrentQuest = "Escape the rocket!"

def on_pause_until2():
    pass


tiles.set_current_tilemap(tilemap("""
    level4
    """))
tiles.place_on_tile(Cat, tiles.get_tile_location(7, 53))
Cat.say_text("I need to launch! hopefully the others can escape...",
    3000,
    False)
CurrentQuest = "Press the button."

def on_pause_until3():
    pass


tiles.set_current_tilemap(tilemap("""
    level5
    """))
tiles.place_on_tile(Cat, tiles.get_tile_location(6, 17))
effects.confetti.end_screen_effect()
effects.star_field.start_screen_effect()
CurrentQuest = "Drift through space."
pause(5000)
Cat.say_text("where am i going.. im terrifed", 3000, False)
pause(3500)
Cat.say_text("ill go ahead and *yawn* sleep... hopefully i wake up on earth... if im lucky",
    7500,
    False)
animation.run_image_animation(Cat,
    [img("""
            ................................
            ................................
            .......................fff......
            ....................fff..f......
            .................fff..f.f.......
            ...................f.f.f........
            ..................f.f..fff......
            .........f.....f.f..fff.........
            .........ff...ff.fff............
            ........f44fff44f...............
            .......f4ff444ff4f..............
            .......f444444444f..............
            .......f44f444f44f..............
            .......f44f4f4f44f..............
            ........f44f4f44f2222...........
            ........f444444ff22222..........
            .........2222222222222..........
            .........f42222244ffff..........
            .........ffff444444f............
            .........f444fffffff............
            .........fff4444444f............
            .......fffffffffffff............
            ......f44ffffffff44f............
            .......fff......ffff............
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            """),
        img("""
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            .........f.....f................
            .........ff...ff................
            ........f44fff44f...............
            .......f44f444f44f..............
            .......f444444444f..............
            .......f44f444f44f....fff.......
            .......f44f4f4f44f....f4f.......
            ........f44f4f44f22222f4f.......
            ........f444444ff22222444f......
            .........2222222222222444f......
            .........f42222244ffff444f......
            .........f444444444f4444ff......
            .........f444444444f44fff.......
            .........f444444444fff..........
            .........fffffffffff............
            .........fffffffffff............
            .........fff.....fff............
            .........f4f.....f4f............
            .........fff.....fff............
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            """)],
    10000,
    False)
pause(10000)
tiles.set_current_tilemap(tilemap("""
    level6
    """))
tiles.place_on_tile(Cat, tiles.get_tile_location(7, 118))
CurrentQuest = "Search the planet for resources."
Cat.say_text("Ummm... where am i..?", 2000, False)
Cat.say_text("This isn't earth...", 2000, False)